### ISSUE TITLE
library name changed for windows between 1.21.0 and 1.21.1

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/blosc-feedstock#55] opened 2022-05-10 17:54 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that users are getting issues with a library name change:
https://github.com/conda-forge/blosc-feedstock/pull/53#issuecomment-1122693303

Apparently GDAL is getting an error when loading the library name:
https://github.com/geopandas/pyogrio/pull/99/files

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by jorisvandenbossche** [comment] 2022-05-10 18:10
To be clear, the failures are for MacOS, not Windows

**Comment by hmaarrfk** [comment] 2022-05-10 18:12
Hmmm. Ok maybe windows has other mechanisms to fix this at runtime.

**Comment by jorisvandenbossche** [comment] 2022-05-10 18:26
I can't edit issues here, but as reported in https://github.com/conda-forge/blosc-feedstock/pull/53#issuecomment-1122080567, we get the following GDAL related error on MacOS CI since last night:

```
ImportError while loading conftest '/Users/runner/work/pyogrio/pyogrio/pyogrio/tests/conftest.py'.
pyogrio/__init__.py:1: in <module>
    from pyogrio.core import (
pyogrio/core.py:6: in <module>
    from pyogrio._ogr import (
E   ImportError: dlopen(/Users/runner/work/pyogrio/pyogrio/pyogrio/_ogr.cpython-39-darwin.so, 2): Symbol not found: _ZSTD_compressBound
E     Referenced from: /Users/runner/micromamba/envs/test/lib/libgdal.30.dylib
E     Expected in: /Users/runner/micromamba/envs/test/lib/libblosc.1.dylib
E    in /Users/runner/micromamba/envs/test/lib/libgdal.30.dylib
```

I also don't have a Mac, so can't reproduce this locally, but the specific environment file that is used on CI is at https://github.com/geopandas/pyogrio/blob/main/ci/environment.yml. But I suppose something like `mamba create -n test python fiona` should be sufficient as well.

From the error message, it seems this has to do with `zstd`, not `snappy`

**Comment by zklaus** [comment] 2022-05-10 20:11
Here is what I think happened: Before the recent change in the conda-forge blosc package, it vendored (among others) zstd and this was baked into the actual libblosc binary. Gdal depends both on blosc and zstd which means that the symbol in question was available from two sources. At linking, it was decided to use the one in blosc. Now we have removed that and there is only one available: the one in zstd. I think that is correct, but it means that gdal needs to be rebuilt. That happened in the poppler rebuild pr, so hopefully, by now the problem has vanished. @jorisvandenbossche, can you check with a ci run from now?

**Comment by jorisvandenbossche** [comment] 2022-05-10 20:16
That's also my understanding. Rerunning CI at https://github.com/geopandas/pyogrio/actions/runs/2297619764

**Comment by zklaus** [comment] 2022-05-10 20:25
Hm. It doesn't seem to work, but it also uses the old build number 6 for libgdal, not the corrected build 7. I don't know why at the moment.

**Comment by jakirkham** [comment] 2022-05-10 20:25
We may also want a repodata hotfix to make sure the existing `gdal` packages don't pick up the new `blosc` package

**Comment by jorisvandenbossche** [comment] 2022-05-10 20:32
> but it also uses the old build number 6 for libgdal, not the corrected build 7.

Might be some cache issue. I triggered another build, now certainly without using the cache: https://github.com/geopandas/pyogrio/pull/100

**Comment by jorisvandenbossche** [comment] 2022-05-10 20:35
Now using gdal build 7, and MacOS CI is green again: https://github.com/geopandas/pyogrio/runs/6377395447?check_suite_focus=true

**Comment by zklaus** [comment] 2022-05-10 20:48
Yepp, that seems to have done the trick.

**Comment by hmaarrfk** [comment] 2022-05-11 03:32
I'm not sure what we want to do about the library name change. It still seems somewhat annoying. But if it is not causing problems, then maybe we can close this issue for windows. Seems like others found other solutions for their issues.

We believe we addressed the root of the issues.

**Comment by zklaus** [comment] 2022-05-12 14:11
I'm gonna go ahead and close this. If you still have problems or see the need for some action, please feel free to reopen.

**Closed by zklaus** 2022-05-12 14:11 UTC
Labels: bug
